name: queer-ai-for-the-ally
services:
  # Caddy - used for HTTPS. Should also handle certificate management from Let's
  # Encrypt with no configuration
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - default_network
    depends_on:
      - openwebui
  # Chat Interface using Open WebUI - https://openwebui.com/.
  # Uses PostgreSQL and PGVector for the database backends. Remember to update
  # CORS_ALLOW_ORIGIN with the hostname.
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.9.6
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - VECTOR_DB=pgvector
      - CORS_ALLOW_ORIGIN=*
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - default_network
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
  # PostgreSQL database to improve the multi-user experience.
  postgres:
    image: pgvector/pgvector:pg17
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  # Ollama for background task -- small models which fit into the CPU.
  ollama:
    image: ollama/ollama:0.15.6
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - default_network
    healthcheck:
      test: ["CMD-SHELL", "ollama list >/dev/null 2>&1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  # Short-lived Ollama service to download a small model for Open WebUI background tasks.
  # Both services use the same volume, so anything pulled here will be available in the
  # other Ollama service.
  ollama-pull:
    container_name: ollama-pull
    image: ollama/ollama:0.15.6
    environment:
      - OLLAMA_HOST=ollama:11434
    volumes:
      - ollama:/root/.ollama
    restart: no
    networks:
      - default_network
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "ollama pull gemma3:1b"
volumes:
  open-webui:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /data/open-webui
  postgres:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /data/postgres
  ollama:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /data/ollama
networks:
  default_network:
